In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Recommend.csv',names=['user_id', 'movie_id', 'rating', 'timestamp'])
df

user_id  movie_id  rating  timestamp
0          196       242       3  881250949
1          186       302       3  891717742
2           22       377       1  878887116
3          244        51       2  880606923
4          166       346       1  886397596
5          298       474       4  884182806
6          115       265       2  881171488
7          253       465       5  891628467
8          305       451       3  886324817
9            6        86       3  883603013
10          62       257       2  879372434
11         286      1014       5  879781125
12         200       222       5  876042340
13         210        40       3  891035994
14         224        29       3  888104457
15         303       785       3  879485318
16         122       387       5  879270459
17         194       274       2  879539794
18         291      1042       4  874834944
19         234      1184       2  892079237
20         119       392       4  886176814
21         167       486       4  892738452
22         299       144       4  877881320
23         291       118       2  874833878
24         308         1       4  887736532
25          95       546       2  879196566
26          38        95       5  892430094
27         102       768       2  883748450
28          63       277       4  875747401
29         160       234       5  876861185
...        ...       ...     ...        ...
99970      449       120       1  879959573
99971      661       762       2  876037121
99972      721       874       3  877137447
99973      821       151       4  874792889
99974      764       596       3  876243046
99975      537       443       3  886031752
99976      618       628       2  891308019
99977      487       291       3  883445079
99978      113       975       5  875936424
99979      943       391       2  888640291
99980      864       685       4  888891900
99981      750       323       3  879445877
99982      279        64       1  875308510
99983      646       750       3  888528902
99984      654       370       2  887863914
99985      617       582       4  883789294
99986      913       690       3  880824288
99987      660       229       2  891406212
99988      421       498       4  892241344
99989      495      1091       4  888637503
99990      806       421       4  882388897
99991      676       538       4  892685437
99992      721       262       3  877137285
99993      913       209       2  881367150
99994      378        78       3  880056976
99995      880       476       3  880175444
99996      716       204       5  879795543
99997      276      1090       1  874795795
99998       13       225       2  882399156
99999       12       203       3  879959583

[100000 rows x 4 columns]

In [3]:
from sklearn.model_selection import train_test_split
n_users = df.user_id.unique().shape[0] 
n_movies = df.movie_id.unique().shape[0]
train_data, test_data = train_test_split(df, test_size=0.25)

In [8]:
train_data_matrix = np.zeros((n_users, n_movies))
for line in train_data.itertuples():
    #[user_id index, movie_id index] = given rating.
    train_data_matrix[line[1]-1, line[2]-1] = line[3] 
train_data_matrix

array([[5., 3., 4., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])

In [9]:
test_data_matrix = np.zeros((n_users, n_movies))
for line in test_data.itertuples():
    #[user_id index, movie_id index] = given rating.
    test_data_matrix[line[1]-1, line[2]-1] = line[3]
test_data_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [11]:
from sklearn.metrics import pairwise_distances
user_similarity = pairwise_distances(train_data_matrix, metric='cosine')
movie_similarity = pairwise_distances(train_data_matrix.T, metric='cosine')
print(user_similarity)
print(movie_similarity)
mean_user_rating = train_data_matrix.mean(axis=1)[:, np.newaxis]
print(mean_user_rating)
ratings_diff = (train_data_matrix - mean_user_rating) 
print(ratings_diff)
user_pred = mean_user_rating + user_similarity.dot(ratings_diff) / np.array([np.abs(user_similarity).sum(axis=1)]).T
print(user_pred)

[[0.         0.86246612 0.98529379 ... 0.8819337  0.87741315 0.72522576]
 [0.86246612 0.         0.85924059 ... 0.87175558 0.85487476 0.91242967]
 [0.98529379 0.85924059 0.         ... 0.91162794 0.87897186 0.97783285]
 ...
 [0.8819337  0.87175558 0.91162794 ... 0.         0.9669666  0.88321032]
 [0.87741315 0.85487476 0.87897186 ... 0.9669666  0.         0.87964494]
 [0.72522576 0.91242967 0.97783285 ... 0.88321032 0.87964494 0.        ]]
[[0.         0.66367268 0.69440049 ... 1.         0.94805195 0.94805195]
 [0.66367268 0.         0.80060952 ... 1.         0.90913262 1.        ]
 [0.69440049 0.80060952 0.         ... 1.         1.         0.89089105]
 ...
 [1.         1.         1.         ... 0.         1.         1.        ]
 [0.94805195 0.90913262 1.         ... 1.         0.         1.        ]
 [0.94805195 1.         0.89089105 ... 1.         1.         0.        ]]
[[0.43638526]
 [0.11058264]
 [0.05648038]
 [0.04875149]
 [0.22413793]
 [0.35850178]
 [0.7491082 ]
 [0.1117717 ]
